-- SQLite Database Schema for Cryptocurrency Trading Bot
-- This schema defines tables for trade journaling, market data storage, and performance tracking

-- Enable foreign key support
PRAGMA foreign_keys = ON;

-- ============================================
-- TRADES TABLE
-- Records of completed trade executions
-- ============================================
CREATE TABLE IF NOT EXISTS trades (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    trade_id TEXT UNIQUE NOT NULL,
    symbol TEXT NOT NULL,
    side TEXT NOT NULL CHECK (side IN ('buy', 'sell', 'long', 'short')),
    entry_price REAL NOT NULL,
    exit_price REAL,
    quantity REAL NOT NULL,
    entry_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    exit_time TIMESTAMP,
    pnl REAL,
    pnl_percent REAL,
    fees REAL DEFAULT 0.0,
    status TEXT NOT NULL CHECK (status IN ('open', 'closed', 'cancelled')),
    strategy TEXT,
    signal_ids TEXT, -- JSON array of signal IDs that triggered this trade
    position_id TEXT, -- Reference to associated position
    metadata TEXT, -- JSON for additional trade metadata
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (position_id) REFERENCES positions(position_id) ON DELETE SET NULL
);

-- Indexes for trades table
CREATE INDEX IF NOT EXISTS idx_trades_symbol ON trades(symbol);
CREATE INDEX IF NOT EXISTS idx_trades_status ON trades(status);
CREATE INDEX IF NOT EXISTS idx_trades_entry_time ON trades(entry_time);
CREATE INDEX IF NOT EXISTS idx_trades_exit_time ON trades(exit_time);
CREATE INDEX IF NOT EXISTS idx_trades_strategy ON trades(strategy);
CREATE INDEX IF NOT EXISTS idx_trades_position_id ON trades(position_id);

-- ============================================
-- SIGNALS TABLE
-- Trading signals generated by the system
-- ============================================
CREATE TABLE IF NOT EXISTS signals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    signal_id TEXT UNIQUE NOT NULL,
    symbol TEXT NOT NULL,
    signal_type TEXT NOT NULL CHECK (signal_type IN ('buy', 'sell', 'neutral', 'strong_buy', 'strong_sell')),
    strength REAL NOT NULL CHECK (strength >= 0 AND strength <= 100),
    indicators TEXT, -- JSON object with indicator values
    price_at_signal REAL NOT NULL,
    volume_at_signal REAL,
    timeframe TEXT,
    strategy TEXT,
    confidence REAL CHECK (confidence >= 0 AND confidence <= 1),
    executed BOOLEAN DEFAULT FALSE,
    trade_id TEXT, -- Reference to trade if executed
    outcome TEXT CHECK (outcome IN ('profit', 'loss', 'neutral', NULL)),
    pnl REAL,
    generated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    executed_at TIMESTAMP,
    expires_at TIMESTAMP,
    metadata TEXT, -- JSON for additional signal metadata
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (trade_id) REFERENCES trades(trade_id) ON DELETE SET NULL
);

-- Indexes for signals table
CREATE INDEX IF NOT EXISTS idx_signals_symbol ON signals(symbol);
CREATE INDEX IF NOT EXISTS idx_signals_type ON signals(signal_type);
CREATE INDEX IF NOT EXISTS idx_signals_generated_at ON signals(generated_at);
CREATE INDEX IF NOT EXISTS idx_signals_executed ON signals(executed);
CREATE INDEX IF NOT EXISTS idx_signals_strategy ON signals(strategy);
CREATE INDEX IF NOT EXISTS idx_signals_trade_id ON signals(trade_id);

-- ============================================
-- POSITIONS TABLE
-- Open and closed position tracking
-- ============================================
CREATE TABLE IF NOT EXISTS positions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    position_id TEXT UNIQUE NOT NULL,
    symbol TEXT NOT NULL,
    side TEXT NOT NULL CHECK (side IN ('long', 'short')),
    size REAL NOT NULL,
    entry_price REAL NOT NULL,
    current_price REAL,
    mark_price REAL,
    stop_loss REAL,
    take_profit REAL,
    liquidation_price REAL,
    unrealized_pnl REAL DEFAULT 0.0,
    realized_pnl REAL DEFAULT 0.0,
    margin_used REAL,
    leverage REAL DEFAULT 1.0,
    status TEXT NOT NULL CHECK (status IN ('open', 'closed', 'liquidated')),
    hedge_id TEXT, -- Reference to associated hedge
    opened_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    metadata TEXT, -- JSON for additional position metadata
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (hedge_id) REFERENCES hedges(hedge_id) ON DELETE SET NULL
);

-- Indexes for positions table
CREATE INDEX IF NOT EXISTS idx_positions_symbol ON positions(symbol);
CREATE INDEX IF NOT EXISTS idx_positions_status ON positions(status);
CREATE INDEX IF NOT EXISTS idx_positions_side ON positions(side);
CREATE INDEX IF NOT EXISTS idx_positions_opened_at ON positions(opened_at);
CREATE INDEX IF NOT EXISTS idx_positions_closed_at ON positions(closed_at);
CREATE INDEX IF NOT EXISTS idx_positions_hedge_id ON positions(hedge_id);

-- ============================================
-- ORDERS TABLE
-- Order execution details
-- ============================================
CREATE TABLE IF NOT EXISTS orders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_id TEXT UNIQUE NOT NULL,
    exchange_order_id TEXT,
    symbol TEXT NOT NULL,
    side TEXT NOT NULL CHECK (side IN ('buy', 'sell')),
    order_type TEXT NOT NULL CHECK (order_type IN ('market', 'limit', 'stop', 'stop_limit', 'trailing_stop')),
    quantity REAL NOT NULL,
    filled_quantity REAL DEFAULT 0.0,
    remaining_quantity REAL,
    price REAL,
    average_fill_price REAL,
    stop_price REAL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'open', 'filled', 'partially_filled', 'cancelled', 'rejected', 'expired')),
    time_in_force TEXT CHECK (time_in_force IN ('GTC', 'IOC', 'FOK', 'PO')),
    fees REAL DEFAULT 0.0,
    fee_currency TEXT,
    trade_id TEXT,
    position_id TEXT,
    signal_id TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    submitted_at TIMESTAMP,
    filled_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    metadata TEXT, -- JSON for additional order metadata
    FOREIGN KEY (trade_id) REFERENCES trades(trade_id) ON DELETE SET NULL,
    FOREIGN KEY (position_id) REFERENCES positions(position_id) ON DELETE SET NULL,
    FOREIGN KEY (signal_id) REFERENCES signals(signal_id) ON DELETE SET NULL
);

-- Indexes for orders table
CREATE INDEX IF NOT EXISTS idx_orders_symbol ON orders(symbol);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_side ON orders(side);
CREATE INDEX IF NOT EXISTS idx_orders_type ON orders(order_type);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at);
CREATE INDEX IF NOT EXISTS idx_orders_trade_id ON orders(trade_id);
CREATE INDEX IF NOT EXISTS idx_orders_position_id ON orders(position_id);

-- ============================================
-- HEDGES TABLE
-- Hedge position records
-- ============================================
CREATE TABLE IF NOT EXISTS hedges (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    hedge_id TEXT UNIQUE NOT NULL,
    primary_position_id TEXT NOT NULL,
    hedge_position_id TEXT NOT NULL,
    primary_symbol TEXT NOT NULL,
    hedge_symbol TEXT NOT NULL,
    correlation_at_hedge REAL,
    hedge_ratio REAL NOT NULL,
    primary_size REAL NOT NULL,
    hedge_size REAL NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('active', 'closed', 'partially_closed')),
    pnl REAL DEFAULT 0.0,
    primary_pnl REAL DEFAULT 0.0,
    hedge_pnl REAL DEFAULT 0.0,
    opened_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP,
    metadata TEXT, -- JSON for additional hedge metadata
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (primary_position_id) REFERENCES positions(position_id) ON DELETE CASCADE,
    FOREIGN KEY (hedge_position_id) REFERENCES positions(position_id) ON DELETE CASCADE
);

-- Indexes for hedges table
CREATE INDEX IF NOT EXISTS idx_hedges_status ON hedges(status);
CREATE INDEX IF NOT EXISTS idx_hedges_primary_symbol ON hedges(primary_symbol);
CREATE INDEX IF NOT EXISTS idx_hedges_hedge_symbol ON hedges(hedge_symbol);
CREATE INDEX IF NOT EXISTS idx_hedges_opened_at ON hedges(opened_at);
CREATE INDEX IF NOT EXISTS idx_hedges_closed_at ON hedges(closed_at);

-- ============================================
-- MARKET_DATA TABLE
-- OHLCV data storage for backtesting and analysis
-- ============================================
CREATE TABLE IF NOT EXISTS market_data (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol TEXT NOT NULL,
    timeframe TEXT NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    open REAL NOT NULL,
    high REAL NOT NULL,
    low REAL NOT NULL,
    close REAL NOT NULL,
    volume REAL NOT NULL,
    quote_volume REAL,
    trades_count INTEGER,
    taker_buy_volume REAL,
    taker_buy_quote_volume REAL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(symbol, timeframe, timestamp)
);

-- Indexes for market_data table
CREATE INDEX IF NOT EXISTS idx_market_data_symbol ON market_data(symbol);
CREATE INDEX IF NOT EXISTS idx_market_data_timeframe ON market_data(timeframe);
CREATE INDEX IF NOT EXISTS idx_market_data_timestamp ON market_data(timestamp);
CREATE INDEX IF NOT EXISTS idx_market_data_symbol_timeframe ON market_data(symbol, timeframe);
CREATE INDEX IF NOT EXISTS idx_market_data_symbol_timeframe_timestamp ON market_data(symbol, timeframe, timestamp);

-- ============================================
-- CORRELATIONS TABLE
-- Correlation calculations between symbols
-- ============================================
CREATE TABLE IF NOT EXISTS correlations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol_a TEXT NOT NULL,
    symbol_b TEXT NOT NULL,
    correlation REAL NOT NULL CHECK (correlation >= -1 AND correlation <= 1),
    correlation_type TEXT NOT NULL CHECK (correlation_type IN ('pearson', 'spearman', 'kendall')),
    timeframe TEXT NOT NULL,
    period INTEGER NOT NULL,
    calculated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    price_data_range_start TIMESTAMP,
    price_data_range_end TIMESTAMP,
    p_value REAL,
    metadata TEXT, -- JSON for additional correlation metadata
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(symbol_a, symbol_b, timeframe, period, calculated_at)
);

-- Indexes for correlations table
CREATE INDEX IF NOT EXISTS idx_correlations_symbol_a ON correlations(symbol_a);
CREATE INDEX IF NOT EXISTS idx_correlations_symbol_b ON correlations(symbol_b);
CREATE INDEX IF NOT EXISTS idx_correlations_timeframe ON correlations(timeframe);
CREATE INDEX IF NOT EXISTS idx_correlations_calculated_at ON correlations(calculated_at);
CREATE INDEX IF NOT EXISTS idx_correlations_symbol_pair ON correlations(symbol_a, symbol_b);

-- ============================================
-- PERFORMANCE TABLE
-- Performance metrics storage
-- ============================================
CREATE TABLE IF NOT EXISTS performance (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    metric_id TEXT UNIQUE NOT NULL,
    metric_type TEXT NOT NULL CHECK (metric_type IN ('daily', 'weekly', 'monthly', 'trade', 'overall')),
    period_start TIMESTAMP NOT NULL,
    period_end TIMESTAMP NOT NULL,
    total_trades INTEGER DEFAULT 0,
    winning_trades INTEGER DEFAULT 0,
    losing_trades INTEGER DEFAULT 0,
    total_pnl REAL DEFAULT 0.0,
    gross_profit REAL DEFAULT 0.0,
    gross_loss REAL DEFAULT 0.0,
    win_rate REAL,
    profit_factor REAL,
    average_win REAL,
    average_loss REAL,
    largest_win REAL,
    largest_loss REAL,
    sharpe_ratio REAL,
    sortino_ratio REAL,
    max_drawdown REAL,
    max_drawdown_percent REAL,
    volatility REAL,
    return_on_investment REAL,
    return_on_investment_percent REAL,
    starting_balance REAL,
    ending_balance REAL,
    metadata TEXT, -- JSON for additional performance metadata
    calculated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance table
CREATE INDEX IF NOT EXISTS idx_performance_metric_type ON performance(metric_type);
CREATE INDEX IF NOT EXISTS idx_performance_period_start ON performance(period_start);
CREATE INDEX IF NOT EXISTS idx_performance_period_end ON performance(period_end);
CREATE INDEX IF NOT EXISTS idx_performance_calculated_at ON performance(calculated_at);

-- ============================================
-- BALANCE_HISTORY TABLE
-- Account balance tracking over time
-- ============================================
CREATE TABLE IF NOT EXISTS balance_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    balance_id TEXT UNIQUE NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_balance REAL NOT NULL,
    available_balance REAL NOT NULL,
    margin_balance REAL,
    unrealized_pnl REAL DEFAULT 0.0,
    realized_pnl_today REAL DEFAULT 0.0,
    realized_pnl_week REAL DEFAULT 0.0,
    realized_pnl_month REAL DEFAULT 0.0,
    currency TEXT DEFAULT 'USD',
    source TEXT, -- e.g., 'exchange', 'calculated', 'manual'
    metadata TEXT, -- JSON for additional balance metadata
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for balance_history table
CREATE INDEX IF NOT EXISTS idx_balance_history_timestamp ON balance_history(timestamp);
CREATE INDEX IF NOT EXISTS idx_balance_history_created_at ON balance_history(created_at);

-- ============================================
-- TRADE_JOURNAL TABLE
-- Detailed trade journal entries for post-analysis
-- ============================================
CREATE TABLE IF NOT EXISTS trade_journal (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    journal_id TEXT UNIQUE NOT NULL,
    trade_id TEXT NOT NULL,
    entry_notes TEXT,
    exit_notes TEXT,
    lessons_learned TEXT,
    emotional_state TEXT,
    market_conditions TEXT,
    setup_quality INTEGER CHECK (setup_quality >= 1 AND setup_quality <= 10),
    execution_quality INTEGER CHECK (execution_quality >= 1 AND execution_quality <= 10),
    tags TEXT, -- JSON array of tags
    screenshots TEXT, -- JSON array of screenshot paths
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (trade_id) REFERENCES trades(trade_id) ON DELETE CASCADE
);

-- Indexes for trade_journal table
CREATE INDEX IF NOT EXISTS idx_trade_journal_trade_id ON trade_journal(trade_id);
CREATE INDEX IF NOT EXISTS idx_trade_journal_created_at ON trade_journal(created_at);

-- ============================================
-- SYSTEM_LOGS TABLE
-- System events and errors logging
-- ============================================
CREATE TABLE IF NOT EXISTS system_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    log_id TEXT UNIQUE NOT NULL,
    level TEXT NOT NULL CHECK (level IN ('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL')),
    component TEXT NOT NULL,
    message TEXT NOT NULL,
    details TEXT, -- JSON for structured log data
    traceback TEXT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for system_logs table
CREATE INDEX IF NOT EXISTS idx_system_logs_level ON system_logs(level);
CREATE INDEX IF NOT EXISTS idx_system_logs_component ON system_logs(component);
CREATE INDEX IF NOT EXISTS idx_system_logs_timestamp ON system_logs(timestamp);

-- ============================================
-- VIEWS FOR COMMON QUERIES
-- ============================================

-- View for open positions with P&L
CREATE VIEW IF NOT EXISTS v_open_positions AS
SELECT 
    p.*,
    CASE 
        WHEN p.side = 'long' THEN (p.current_price - p.entry_price) * p.size
        ELSE (p.entry_price - p.current_price) * p.size
    END as calculated_unrealized_pnl,
    CASE 
        WHEN p.side = 'long' THEN ((p.current_price - p.entry_price) / p.entry_price) * 100
        ELSE ((p.entry_price - p.current_price) / p.entry_price) * 100
    END as calculated_unrealized_pnl_percent
FROM positions p
WHERE p.status = 'open';

-- View for trade statistics by symbol
CREATE VIEW IF NOT EXISTS v_trade_stats_by_symbol AS
SELECT 
    symbol,
    COUNT(*) as total_trades,
    SUM(CASE WHEN pnl > 0 THEN 1 ELSE 0 END) as winning_trades,
    SUM(CASE WHEN pnl < 0 THEN 1 ELSE 0 END) as losing_trades,
    SUM(CASE WHEN pnl > 0 THEN pnl ELSE 0 END) as gross_profit,
    SUM(CASE WHEN pnl < 0 THEN pnl ELSE 0 END) as gross_loss,
    SUM(pnl) as total_pnl,
    AVG(pnl) as average_pnl,
    AVG(CASE WHEN pnl > 0 THEN pnl END) as average_win,
    AVG(CASE WHEN pnl < 0 THEN pnl END) as average_loss,
    MAX(pnl) as largest_win,
    MIN(pnl) as largest_loss,
    AVG(pnl_percent) as average_pnl_percent
FROM trades
WHERE status = 'closed'
GROUP BY symbol;

-- View for daily P&L summary
CREATE VIEW IF NOT EXISTS v_daily_pnl AS
SELECT 
    DATE(exit_time) as date,
    COUNT(*) as trades_count,
    SUM(pnl) as total_pnl,
    SUM(fees) as total_fees,
    SUM(pnl - fees) as net_pnl,
    AVG(pnl_percent) as avg_pnl_percent
FROM trades
WHERE status = 'closed' AND exit_time IS NOT NULL
GROUP BY DATE(exit_time)
ORDER BY date DESC;
